[package]
name = "bump-version"
version = "0.4.0"
edition = "2024"

[dependencies]
git2 = "0.20"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]

[dependencies.indexmap]
version = "2.9"
features = ["serde"]
